openapi: 3.0.0
info:
  title: Cinema Bookings API
  version: 0.0.1
host: localhost:4040
basePath: /
schemes:
  - http
paths:
  /movies:
    get:
      summary: Retrieve a list of movies
      produces:
        - application/json
      responses:
        200:
          description: OK
          content: 
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/MovieWithScreenings'
    post:
      summary: Create a movie
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                runtimeMins:
                  type: interger
            example:
              title: The Matrix
              runtimeMins: 136
      responses:
        400:
          description: Bad request. One or more of the required fields are missing or invalid.
        200:
          description: OK
          content: 
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    $ref: "#/components/schemas/Movie"
              example:
                data:
                  id: 1
                  title: The Matrix
                  runtimeMins: 136
                  createdAt: 2022-06-09T08:49:28.952Z
                  updatedAt: 2022-06-09T08:49:28.952Z
  /movies/{movieId}:
    get:
      summary: Get a movie by ID
      produces:
        - application/json
      responses:
        404: 
          description: The requested Movie could not be found.
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    $ref: "#/components/schemas/MovieWithScreenings"

components:
  schemas:
    Screening:
      type: object
      properties:
        id:
          type: integer
        movieId: 
          type: integer
        screenId: 
          type: integer
        createdAt:
          type: string
        updatedAt: 
          type: string
    Movie:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        runtimeMins:
          type: integer
        createdAt:
          type: string
        updatedAt:
          type: string
    MovieWithScreenings:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        runtimeMins:
          type: integer
        screenings:
          type: array
          items:
            $ref: '#/components/schemas/Screening'
        createdAt:
          type: string
        updatedAt:
          type: string
